[package]
name = "spatialos-gdk"
version = "0.1.0"
authors = ["sam <samsnyder96@gmail.com>"]

build = "src/build.rs"

[dependencies]
libc = "0.2.0"
downcast-rs = "1.0.3"
boxfnonce = "0.1.0"
rayon = "1.0"

[build-dependencies]
bindgen = "0.40.0"